apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: erp-backend-hpa
  namespace: erp-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: erp-backend-app   #  #deployment name  of fronted
  minReplicas: 1             
  maxReplicas: 2            
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70   # 70% CPU usage pe scale hoga
