apiVersion: v1
kind: ConfigMap
metadata:
  name: erp-config
  namespace: erp-ns
data:
  MYSQL_DATABASE: school_erp_db
  DB_HOST: mysql-svc.erp-ns.svc.cluster.local
  NODE_ENV: production
  DB_USER: root 
  DB_NAME: school_erp_db
  PORT: '5000'
