apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: erp-frontend-hpa
  namespace: erp-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: erp-fronted-app    
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
