server {
    listen 80;

    server_name _;

    root /usr/share/nginx/html;

    index index.html;

    location /apps {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri /index.html;   # 👈 this makes React Router work
    }

    location / {
        root   /usr/share/nginx/html;
        index  index.html;
    }
}
